// Autogenerated from Pigeon (v29.0.2), do not edit directly.
// See also: https://pub.dev/packages/pigeon

import Foundation

#if os(iOS)
  import Flutter
#elseif os(macOS)
  import FlutterMacOS
#else
  #error("Unsupported platform.")
#endif

/// Error class for passing custom error details to Dart side.
final class PigeonError: Error {
  let code: String
  let message: String?
  let details: Sendable?

  init(code: String, message: String?, details: Sendable?) {
    self.code = code
    self.message = message
    self.details = details
  }

  var localizedDescription: String {
    return
      "PigeonError(code: \(code), message: \(message ?? "<nil>"), details: \(details ?? "<nil>"))"
  }
}

private func wrapResult(_ result: Any?) -> [Any?] {
  return [result]
}

private func wrapError(_ error: Any) -> [Any?] {
  if let pigeonError = error as? PigeonError {
    return [
      pigeonError.code,
      pigeonError.message,
      pigeonError.details,
    ]
  }
  if let flutterError = error as? FlutterError {
    return [
      flutterError.code,
      flutterError.message,
      flutterError.details,
    ]
  }
  return [
    "\(error)",
    "\(Swift.type(of: error))",
    "Stacktrace: \(Thread.callStackSymbols)",
  ]
}

private func createConnectionError(withChannelName channelName: String) -> PigeonError {
  return PigeonError(code: "channel-error", message: "Unable to establish connection on channel: '\(channelName)'.", details: "")
}

enum EngineApiPigeonInternal {
  static func isNullish(_ value: Any?) -> Bool {
    guard let innerValue = value else {
      return true
    }

    if case Optional<Any>.some(Optional<Any>.none) = value {
      return true
    }

    return innerValue is NSNull
  }
  static func doubleEquals(_ lhs: Double, _ rhs: Double) -> Bool {
    return (lhs.isNaN && rhs.isNaN) || lhs == rhs
  }

  static func doubleHash(_ value: Double, _ hasher: inout Hasher) {
    if value.isNaN {
      hasher.combine(0x7FF8000000000000)
    } else {
      // Normalize -0.0 to 0.0
      hasher.combine(value == 0 ? 0 : value)
    }
  }

  static func deepEquals(_ lhs: Any?, _ rhs: Any?) -> Bool {
    let cleanLhs = nilOrValue(lhs) as Any?
    let cleanRhs = nilOrValue(rhs) as Any?
    switch (cleanLhs, cleanRhs) {
    case (nil, nil):
      return true

    case (nil, _), (_, nil):
      return false

    case (let lhs as AnyObject, let rhs as AnyObject) where lhs === rhs:
      return true

    case is (Void, Void):
      return true

    case (let lhsArray, let rhsArray) as ([Double], [Double]):
      guard lhsArray.count == rhsArray.count else { return false }
      for (index, element) in lhsArray.enumerated() {
        if !doubleEquals(element, rhsArray[index]) {
          return false
        }
      }
      return true

    case (let lhsArray, let rhsArray) as ([Any?], [Any?]):
      guard lhsArray.count == rhsArray.count else { return false }
      for (index, element) in lhsArray.enumerated() {
        if !deepEquals(element, rhsArray[index]) {
          return false
        }
      }
      return true

    case (let lhsDictionary, let rhsDictionary) as ([AnyHashable: Any?], [AnyHashable: Any?]):
      guard lhsDictionary.count == rhsDictionary.count else { return false }
      for (lhsKey, lhsValue) in lhsDictionary {
        var found = false
        for (rhsKey, rhsValue) in rhsDictionary {
          if deepEquals(lhsKey, rhsKey) {
            if deepEquals(lhsValue, rhsValue) {
              found = true
              break
            } else {
              return false
            }
          }
        }
        if !found { return false }
      }
      return true

    case (let lhs as Double, let rhs as Double):
      return doubleEquals(lhs, rhs)

    case (let lhsHashable, let rhsHashable) as (AnyHashable, AnyHashable):
      return lhsHashable == rhsHashable

    default:
      return false
    }
  }

  static func deepHash(value: Any?, hasher: inout Hasher) {
    let cleanValue = nilOrValue(value) as Any?
    if let cleanValue = cleanValue {
      if let doubleValue = cleanValue as? Double {
        doubleHash(doubleValue, &hasher)
      } else if let valueList = cleanValue as? [Any?] {
        for item in valueList {
          deepHash(value: item, hasher: &hasher)
        }
      } else if let valueList = cleanValue as? [Double] {
        for item in valueList {
          doubleHash(item, &hasher)
        }
      } else if let valueDict = cleanValue as? [AnyHashable: Any?] {
        var result = 0
        for (key, value) in valueDict {
          var entryKeyHasher = Hasher()
          deepHash(value: key, hasher: &entryKeyHasher)
          var entryValueHasher = Hasher()
          deepHash(value: value, hasher: &entryValueHasher)
          result = result &+ ((entryKeyHasher.finalize() &* 31) ^ entryValueHasher.finalize())
        }
        hasher.combine(result)
      } else if let hashableValue = cleanValue as? AnyHashable {
        hasher.combine(hashableValue)
      } else {
        hasher.combine(String(describing: cleanValue))
      }
    } else {
      hasher.combine(0)
    }
  }

}

private func nilOrValue<T>(_ value: Any?) -> T? {
  if value is NSNull { return nil }
  return value as! T?
}


/// What a media file contains, from the file itself.
///
/// Generated class from Pigeon that represents data sent in messages.
struct MediaInfoMessage: Hashable, CustomStringConvertible {
  /// Null for still images.
  var durationUs: Int64? = nil
  /// Display size, after applying [rotationDeg].
  var width: Int64
  var height: Int64
  var rotationDeg: Int64
  /// Nominal frame rate; zero for stills and audio.
  var frameRate: Double
  var hasVideo: Bool
  var hasAudio: Bool
  var isHdr: Bool


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> MediaInfoMessage? {
    let durationUs: Int64? = nilOrValue(pigeonVar_list[0])
    let width = pigeonVar_list[1] as! Int64
    let height = pigeonVar_list[2] as! Int64
    let rotationDeg = pigeonVar_list[3] as! Int64
    let frameRate = pigeonVar_list[4] as! Double
    let hasVideo = pigeonVar_list[5] as! Bool
    let hasAudio = pigeonVar_list[6] as! Bool
    let isHdr = pigeonVar_list[7] as! Bool

    return MediaInfoMessage(
      durationUs: durationUs,
      width: width,
      height: height,
      rotationDeg: rotationDeg,
      frameRate: frameRate,
      hasVideo: hasVideo,
      hasAudio: hasAudio,
      isHdr: isHdr
    )
  }
  func toList() -> [Any?] {
    return [
      durationUs,
      width,
      height,
      rotationDeg,
      frameRate,
      hasVideo,
      hasAudio,
      isHdr,
    ]
  }
  static func == (lhs: MediaInfoMessage, rhs: MediaInfoMessage) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return EngineApiPigeonInternal.deepEquals(lhs.durationUs, rhs.durationUs) && EngineApiPigeonInternal.deepEquals(lhs.width, rhs.width) && EngineApiPigeonInternal.deepEquals(lhs.height, rhs.height) && EngineApiPigeonInternal.deepEquals(lhs.rotationDeg, rhs.rotationDeg) && EngineApiPigeonInternal.deepEquals(lhs.frameRate, rhs.frameRate) && EngineApiPigeonInternal.deepEquals(lhs.hasVideo, rhs.hasVideo) && EngineApiPigeonInternal.deepEquals(lhs.hasAudio, rhs.hasAudio) && EngineApiPigeonInternal.deepEquals(lhs.isHdr, rhs.isHdr)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("MediaInfoMessage")
    EngineApiPigeonInternal.deepHash(value: durationUs, hasher: &hasher)
    EngineApiPigeonInternal.deepHash(value: width, hasher: &hasher)
    EngineApiPigeonInternal.deepHash(value: height, hasher: &hasher)
    EngineApiPigeonInternal.deepHash(value: rotationDeg, hasher: &hasher)
    EngineApiPigeonInternal.deepHash(value: frameRate, hasher: &hasher)
    EngineApiPigeonInternal.deepHash(value: hasVideo, hasher: &hasher)
    EngineApiPigeonInternal.deepHash(value: hasAudio, hasher: &hasher)
    EngineApiPigeonInternal.deepHash(value: isHdr, hasher: &hasher)
  }

  public var description: String {
    return "MediaInfoMessage(durationUs: \(String(describing: durationUs)), width: \(String(describing: width)), height: \(String(describing: height)), rotationDeg: \(String(describing: rotationDeg)), frameRate: \(String(describing: frameRate)), hasVideo: \(String(describing: hasVideo)), hasAudio: \(String(describing: hasAudio)), isHdr: \(String(describing: isHdr)))"
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct CapabilitiesMessage: Hashable, CustomStringConvertible {
  var hevc: Bool
  var max4k: Bool


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> CapabilitiesMessage? {
    let hevc = pigeonVar_list[0] as! Bool
    let max4k = pigeonVar_list[1] as! Bool

    return CapabilitiesMessage(
      hevc: hevc,
      max4k: max4k
    )
  }
  func toList() -> [Any?] {
    return [
      hevc,
      max4k,
    ]
  }
  static func == (lhs: CapabilitiesMessage, rhs: CapabilitiesMessage) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return EngineApiPigeonInternal.deepEquals(lhs.hevc, rhs.hevc) && EngineApiPigeonInternal.deepEquals(lhs.max4k, rhs.max4k)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("CapabilitiesMessage")
    EngineApiPigeonInternal.deepHash(value: hevc, hasher: &hasher)
    EngineApiPigeonInternal.deepHash(value: max4k, hasher: &hasher)
  }

  public var description: String {
    return "CapabilitiesMessage(hevc: \(String(describing: hevc)), max4k: \(String(describing: max4k)))"
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct ExportRequestMessage: Hashable, CustomStringConvertible {
  var outputPath: String
  var width: Int64
  var height: Int64
  var frameRate: Int64
  var videoBitrate: Int64
  var hevc: Bool


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> ExportRequestMessage? {
    let outputPath = pigeonVar_list[0] as! String
    let width = pigeonVar_list[1] as! Int64
    let height = pigeonVar_list[2] as! Int64
    let frameRate = pigeonVar_list[3] as! Int64
    let videoBitrate = pigeonVar_list[4] as! Int64
    let hevc = pigeonVar_list[5] as! Bool

    return ExportRequestMessage(
      outputPath: outputPath,
      width: width,
      height: height,
      frameRate: frameRate,
      videoBitrate: videoBitrate,
      hevc: hevc
    )
  }
  func toList() -> [Any?] {
    return [
      outputPath,
      width,
      height,
      frameRate,
      videoBitrate,
      hevc,
    ]
  }
  static func == (lhs: ExportRequestMessage, rhs: ExportRequestMessage) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return EngineApiPigeonInternal.deepEquals(lhs.outputPath, rhs.outputPath) && EngineApiPigeonInternal.deepEquals(lhs.width, rhs.width) && EngineApiPigeonInternal.deepEquals(lhs.height, rhs.height) && EngineApiPigeonInternal.deepEquals(lhs.frameRate, rhs.frameRate) && EngineApiPigeonInternal.deepEquals(lhs.videoBitrate, rhs.videoBitrate) && EngineApiPigeonInternal.deepEquals(lhs.hevc, rhs.hevc)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("ExportRequestMessage")
    EngineApiPigeonInternal.deepHash(value: outputPath, hasher: &hasher)
    EngineApiPigeonInternal.deepHash(value: width, hasher: &hasher)
    EngineApiPigeonInternal.deepHash(value: height, hasher: &hasher)
    EngineApiPigeonInternal.deepHash(value: frameRate, hasher: &hasher)
    EngineApiPigeonInternal.deepHash(value: videoBitrate, hasher: &hasher)
    EngineApiPigeonInternal.deepHash(value: hevc, hasher: &hasher)
  }

  public var description: String {
    return "ExportRequestMessage(outputPath: \(String(describing: outputPath)), width: \(String(describing: width)), height: \(String(describing: height)), frameRate: \(String(describing: frameRate)), videoBitrate: \(String(describing: videoBitrate)), hevc: \(String(describing: hevc)))"
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct PlaybackStateMessage: Hashable, CustomStringConvertible {
  var positionUs: Int64
  var durationUs: Int64
  var isPlaying: Bool
  var isBuffering: Bool


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> PlaybackStateMessage? {
    let positionUs = pigeonVar_list[0] as! Int64
    let durationUs = pigeonVar_list[1] as! Int64
    let isPlaying = pigeonVar_list[2] as! Bool
    let isBuffering = pigeonVar_list[3] as! Bool

    return PlaybackStateMessage(
      positionUs: positionUs,
      durationUs: durationUs,
      isPlaying: isPlaying,
      isBuffering: isBuffering
    )
  }
  func toList() -> [Any?] {
    return [
      positionUs,
      durationUs,
      isPlaying,
      isBuffering,
    ]
  }
  static func == (lhs: PlaybackStateMessage, rhs: PlaybackStateMessage) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return EngineApiPigeonInternal.deepEquals(lhs.positionUs, rhs.positionUs) && EngineApiPigeonInternal.deepEquals(lhs.durationUs, rhs.durationUs) && EngineApiPigeonInternal.deepEquals(lhs.isPlaying, rhs.isPlaying) && EngineApiPigeonInternal.deepEquals(lhs.isBuffering, rhs.isBuffering)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("PlaybackStateMessage")
    EngineApiPigeonInternal.deepHash(value: positionUs, hasher: &hasher)
    EngineApiPigeonInternal.deepHash(value: durationUs, hasher: &hasher)
    EngineApiPigeonInternal.deepHash(value: isPlaying, hasher: &hasher)
    EngineApiPigeonInternal.deepHash(value: isBuffering, hasher: &hasher)
  }

  public var description: String {
    return "PlaybackStateMessage(positionUs: \(String(describing: positionUs)), durationUs: \(String(describing: durationUs)), isPlaying: \(String(describing: isPlaying)), isBuffering: \(String(describing: isBuffering)))"
  }
}

private class EngineApiPigeonCodecReader: FlutterStandardReader {
  override func readValue(ofType type: UInt8) -> Any? {
    switch type {
    case 129:
      return MediaInfoMessage.fromList(self.readValue() as! [Any?])
    case 130:
      return CapabilitiesMessage.fromList(self.readValue() as! [Any?])
    case 131:
      return ExportRequestMessage.fromList(self.readValue() as! [Any?])
    case 132:
      return PlaybackStateMessage.fromList(self.readValue() as! [Any?])
    default:
      return super.readValue(ofType: type)
    }
  }
}

private class EngineApiPigeonCodecWriter: FlutterStandardWriter {
  override func writeValue(_ value: Any) {
    if let value = value as? MediaInfoMessage {
      super.writeByte(129)
      super.writeValue(value.toList())
    } else if let value = value as? CapabilitiesMessage {
      super.writeByte(130)
      super.writeValue(value.toList())
    } else if let value = value as? ExportRequestMessage {
      super.writeByte(131)
      super.writeValue(value.toList())
    } else if let value = value as? PlaybackStateMessage {
      super.writeByte(132)
      super.writeValue(value.toList())
    } else {
      super.writeValue(value)
    }
  }
}

private class EngineApiPigeonCodecReaderWriter: FlutterStandardReaderWriter {
  override func reader(with data: Data) -> FlutterStandardReader {
    return EngineApiPigeonCodecReader(data: data)
  }

  override func writer(with data: NSMutableData) -> FlutterStandardWriter {
    return EngineApiPigeonCodecWriter(data: data)
  }
}

class EngineApiPigeonCodec: FlutterStandardMessageCodec, @unchecked Sendable {
  static let shared = EngineApiPigeonCodec(readerWriter: EngineApiPigeonCodecReaderWriter())
}


/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol EngineHostApi {
  /// Creates the preview surface; returns the Flutter texture id.
  func createPreview() throws -> Int64
  /// Replaces the document being previewed. See `EngineDocument` in Dart.
  func setDocument(json: String) throws
  func play() throws
  func pause() throws
  /// [exact] false allows landing near the time, for fast scrubbing.
  func seek(positionUs: Int64, exact: Bool) throws
  /// Releases players, decoders, and caches. Safe to call repeatedly.
  func release() throws
  func probe(path: String) async throws -> MediaInfoMessage
  /// Writes a JPEG per time into [outDir], each at most [maxSize] pixels on
  /// its longest side, and returns their paths in order (null on failure).
  func thumbnails(path: String, timesUs: [Int64], maxSize: Int64, outDir: String) async throws -> [String?]
  /// Writes a 720p copy of [path] to [outPath] for smooth preview.
  func createProxy(path: String, outPath: String) async throws
  func capabilities() throws -> CapabilitiesMessage
  /// Starts exporting the current document; progress arrives through
  /// [EngineFlutterApi]. Returns a job id.
  func startExport(request: ExportRequestMessage) throws -> String
  func cancelExport(jobId: String) throws
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class EngineHostApiSetup {
  static var codec: FlutterStandardMessageCodec { EngineApiPigeonCodec.shared }
  /// Sets up an instance of `EngineHostApi` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: EngineHostApi?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    /// Creates the preview surface; returns the Flutter texture id.
    let createPreviewChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.stitch.EngineHostApi.createPreview\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      createPreviewChannel.setMessageHandler { _, reply in
        do {
          let result = try api.createPreview()
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      createPreviewChannel.setMessageHandler(nil)
    }
    /// Replaces the document being previewed. See `EngineDocument` in Dart.
    let setDocumentChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.stitch.EngineHostApi.setDocument\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      setDocumentChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let jsonArg = args[0] as! String
        do {
          try api.setDocument(json: jsonArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      setDocumentChannel.setMessageHandler(nil)
    }
    let playChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.stitch.EngineHostApi.play\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      playChannel.setMessageHandler { _, reply in
        do {
          try api.play()
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      playChannel.setMessageHandler(nil)
    }
    let pauseChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.stitch.EngineHostApi.pause\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      pauseChannel.setMessageHandler { _, reply in
        do {
          try api.pause()
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      pauseChannel.setMessageHandler(nil)
    }
    /// [exact] false allows landing near the time, for fast scrubbing.
    let seekChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.stitch.EngineHostApi.seek\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      seekChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let positionUsArg = args[0] as! Int64
        let exactArg = args[1] as! Bool
        do {
          try api.seek(positionUs: positionUsArg, exact: exactArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      seekChannel.setMessageHandler(nil)
    }
    /// Releases players, decoders, and caches. Safe to call repeatedly.
    let releaseChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.stitch.EngineHostApi.release\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      releaseChannel.setMessageHandler { _, reply in
        do {
          try api.release()
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      releaseChannel.setMessageHandler(nil)
    }
    let probeChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.stitch.EngineHostApi.probe\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      probeChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let pathArg = args[0] as! String
        Task { @MainActor in
          do {
            let result = try await api.probe(path: pathArg)
            reply(wrapResult(result))
          } catch {
            reply(wrapError(error))
          }
        }
      }
    } else {
      probeChannel.setMessageHandler(nil)
    }
    /// Writes a JPEG per time into [outDir], each at most [maxSize] pixels on
    /// its longest side, and returns their paths in order (null on failure).
    let thumbnailsChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.stitch.EngineHostApi.thumbnails\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      thumbnailsChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let pathArg = args[0] as! String
        let timesUsArg = args[1] as! [Int64]
        let maxSizeArg = args[2] as! Int64
        let outDirArg = args[3] as! String
        Task { @MainActor in
          do {
            let result = try await api.thumbnails(path: pathArg, timesUs: timesUsArg, maxSize: maxSizeArg, outDir: outDirArg)
            reply(wrapResult(result))
          } catch {
            reply(wrapError(error))
          }
        }
      }
    } else {
      thumbnailsChannel.setMessageHandler(nil)
    }
    /// Writes a 720p copy of [path] to [outPath] for smooth preview.
    let createProxyChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.stitch.EngineHostApi.createProxy\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      createProxyChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let pathArg = args[0] as! String
        let outPathArg = args[1] as! String
        Task { @MainActor in
          do {
            try await api.createProxy(path: pathArg, outPath: outPathArg)
            reply(wrapResult(nil))
          } catch {
            reply(wrapError(error))
          }
        }
      }
    } else {
      createProxyChannel.setMessageHandler(nil)
    }
    let capabilitiesChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.stitch.EngineHostApi.capabilities\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      capabilitiesChannel.setMessageHandler { _, reply in
        do {
          let result = try api.capabilities()
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      capabilitiesChannel.setMessageHandler(nil)
    }
    /// Starts exporting the current document; progress arrives through
    /// [EngineFlutterApi]. Returns a job id.
    let startExportChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.stitch.EngineHostApi.startExport\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      startExportChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let requestArg = args[0] as! ExportRequestMessage
        do {
          let result = try api.startExport(request: requestArg)
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      startExportChannel.setMessageHandler(nil)
    }
    let cancelExportChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.stitch.EngineHostApi.cancelExport\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      cancelExportChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let jobIdArg = args[0] as! String
        do {
          try api.cancelExport(jobId: jobIdArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      cancelExportChannel.setMessageHandler(nil)
    }
  }
}

/// Generated protocol from Pigeon that represents Flutter messages that can be called from Swift.
protocol EngineFlutterApiProtocol {
  @MainActor func onPlaybackState(state stateArg: PlaybackStateMessage) async throws
  @MainActor func onExportProgress(jobId jobIdArg: String, fraction fractionArg: Double) async throws
  @MainActor func onExportCompleted(jobId jobIdArg: String, outputPath outputPathArg: String) async throws
  /// [code] is stable (for mapping to a message); [message] is for logs.
  @MainActor func onExportFailed(jobId jobIdArg: String, code codeArg: String, message messageArg: String) async throws
}
class EngineFlutterApi: EngineFlutterApiProtocol {
  private let binaryMessenger: FlutterBinaryMessenger
  private let messageChannelSuffix: String
  init(binaryMessenger: FlutterBinaryMessenger, messageChannelSuffix: String = "") {
    self.binaryMessenger = binaryMessenger
    self.messageChannelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
  }
  var codec: EngineApiPigeonCodec {
    return EngineApiPigeonCodec.shared
  }
  @MainActor func onPlaybackState(state stateArg: PlaybackStateMessage) async throws {
    return try await withCheckedThrowingContinuation { continuation in
      let channelName: String = "dev.flutter.pigeon.stitch.EngineFlutterApi.onPlaybackState\(messageChannelSuffix)"
      let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
      channel.sendMessage([stateArg] as [Any?]) { response in
        guard let listResponse = response as? [Any?] else {
          continuation.resume(throwing: createConnectionError(withChannelName: channelName))
          return
        }
        if listResponse.count > 1 {
          let code: String = listResponse[0] as! String
          let message: String? = nilOrValue(listResponse[1])
          let details: String? = nilOrValue(listResponse[2])
          continuation.resume(throwing: PigeonError(code: code, message: message, details: details))
        } else {
          continuation.resume()
        }
      }
    }
  }
  @MainActor func onExportProgress(jobId jobIdArg: String, fraction fractionArg: Double) async throws {
    return try await withCheckedThrowingContinuation { continuation in
      let channelName: String = "dev.flutter.pigeon.stitch.EngineFlutterApi.onExportProgress\(messageChannelSuffix)"
      let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
      channel.sendMessage([jobIdArg, fractionArg] as [Any?]) { response in
        guard let listResponse = response as? [Any?] else {
          continuation.resume(throwing: createConnectionError(withChannelName: channelName))
          return
        }
        if listResponse.count > 1 {
          let code: String = listResponse[0] as! String
          let message: String? = nilOrValue(listResponse[1])
          let details: String? = nilOrValue(listResponse[2])
          continuation.resume(throwing: PigeonError(code: code, message: message, details: details))
        } else {
          continuation.resume()
        }
      }
    }
  }
  @MainActor func onExportCompleted(jobId jobIdArg: String, outputPath outputPathArg: String) async throws {
    return try await withCheckedThrowingContinuation { continuation in
      let channelName: String = "dev.flutter.pigeon.stitch.EngineFlutterApi.onExportCompleted\(messageChannelSuffix)"
      let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
      channel.sendMessage([jobIdArg, outputPathArg] as [Any?]) { response in
        guard let listResponse = response as? [Any?] else {
          continuation.resume(throwing: createConnectionError(withChannelName: channelName))
          return
        }
        if listResponse.count > 1 {
          let code: String = listResponse[0] as! String
          let message: String? = nilOrValue(listResponse[1])
          let details: String? = nilOrValue(listResponse[2])
          continuation.resume(throwing: PigeonError(code: code, message: message, details: details))
        } else {
          continuation.resume()
        }
      }
    }
  }
  /// [code] is stable (for mapping to a message); [message] is for logs.
  @MainActor func onExportFailed(jobId jobIdArg: String, code codeArg: String, message messageArg: String) async throws {
    return try await withCheckedThrowingContinuation { continuation in
      let channelName: String = "dev.flutter.pigeon.stitch.EngineFlutterApi.onExportFailed\(messageChannelSuffix)"
      let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
      channel.sendMessage([jobIdArg, codeArg, messageArg] as [Any?]) { response in
        guard let listResponse = response as? [Any?] else {
          continuation.resume(throwing: createConnectionError(withChannelName: channelName))
          return
        }
        if listResponse.count > 1 {
          let code: String = listResponse[0] as! String
          let message: String? = nilOrValue(listResponse[1])
          let details: String? = nilOrValue(listResponse[2])
          continuation.resume(throwing: PigeonError(code: code, message: message, details: details))
        } else {
          continuation.resume()
        }
      }
    }
  }
}
