// Generated by tool/gen_transitions.dart from transitions/*.glsl. Do not edit.

/// Each transition as Metal: `float4 transition(CTX_PARAMS, float2 uv)` and
/// its helpers, which Transitions.swift wraps in its prelude and kernel.
enum TransitionSources {
  static let metal: [String: String] = [
    "crossfade": #"""
    vec4 transition(CTX_PARAMS, vec2 uv) {
      return mix(getFromColor(uv), getToColor(uv), progress);
    }
    """#,
    "fadeToBlack": #"""
    vec4 transition(CTX_PARAMS, vec2 uv) {
      vec4 black = vec4(0.0, 0.0, 0.0, 1.0);
      return progress < 0.5
        ? mix(getFromColor(uv), black, progress * 2.0)
        : mix(black, getToColor(uv), progress * 2.0 - 1.0);
    }
    """#,
    "fadeToWhite": #"""
    vec4 transition(CTX_PARAMS, vec2 uv) {
      vec4 white = vec4(1.0, 1.0, 1.0, 1.0);
      return progress < 0.5
        ? mix(getFromColor(uv), white, progress * 2.0)
        : mix(white, getToColor(uv), progress * 2.0 - 1.0);
    }
    """#,
    "dissolve": #"""
    float hash(CTX_PARAMS, vec2 p) {
      vec3 p3 = fract(vec3(p.x, p.y, p.x) * 0.1031);
      p3 += dot(p3, vec3(p3.y, p3.z, p3.x) + 33.33);
      return fract((p3.x + p3.y) * p3.z);
    }

    #define CELLS 80.0

    vec4 transition(CTX_PARAMS, vec2 uv) {
      float n = hash(CTX_ARGS, floor(uv * vec2(CELLS * ratio, CELLS)));
      float t = smoothstep(n - 0.05, n + 0.05, progress * 1.1 - 0.05);
      return mix(getFromColor(uv), getToColor(uv), t);
    }
    """#,
    "lumaFade": #"""
    vec4 transition(CTX_PARAMS, vec2 uv) {
      vec4 a = getFromColor(uv);
      vec4 b = getToColor(uv);
      float l = 1.0 - dot(a.rgb, vec3(0.299, 0.587, 0.114));
      float t = smoothstep(l - 0.1, l + 0.1, progress * 1.2 - 0.1);
      return mix(a, b, t);
    }
    """#,
    "slideLeft": #"""
    vec4 transition(CTX_PARAMS, vec2 uv) {
      return uv.x < 1.0 - progress
        ? getFromColor(vec2(uv.x + progress, uv.y))
        : getToColor(vec2(uv.x - (1.0 - progress), uv.y));
    }
    """#,
    "slideRight": #"""
    vec4 transition(CTX_PARAMS, vec2 uv) {
      return uv.x >= progress
        ? getFromColor(vec2(uv.x - progress, uv.y))
        : getToColor(vec2(uv.x + (1.0 - progress), uv.y));
    }
    """#,
    "slideUp": #"""
    vec4 transition(CTX_PARAMS, vec2 uv) {
      return uv.y >= progress
        ? getFromColor(vec2(uv.x, uv.y - progress))
        : getToColor(vec2(uv.x, uv.y + (1.0 - progress)));
    }
    """#,
    "slideDown": #"""
    vec4 transition(CTX_PARAMS, vec2 uv) {
      return uv.y < 1.0 - progress
        ? getFromColor(vec2(uv.x, uv.y + progress))
        : getToColor(vec2(uv.x, uv.y - (1.0 - progress)));
    }
    """#,
    "coverLeft": #"""
    vec4 transition(CTX_PARAMS, vec2 uv) {
      return uv.x >= 1.0 - progress
        ? getToColor(vec2(uv.x - (1.0 - progress), uv.y))
        : getFromColor(uv);
    }
    """#,
    "coverRight": #"""
    vec4 transition(CTX_PARAMS, vec2 uv) {
      return uv.x < progress
        ? getToColor(vec2(uv.x + (1.0 - progress), uv.y))
        : getFromColor(uv);
    }
    """#,
    "revealLeft": #"""
    vec4 transition(CTX_PARAMS, vec2 uv) {
      return uv.x < 1.0 - progress
        ? getFromColor(vec2(uv.x + progress, uv.y))
        : getToColor(uv);
    }
    """#,
    "revealRight": #"""
    vec4 transition(CTX_PARAMS, vec2 uv) {
      return uv.x >= progress
        ? getFromColor(vec2(uv.x - progress, uv.y))
        : getToColor(uv);
    }
    """#,
    "wipeLeft": #"""
    vec4 transition(CTX_PARAMS, vec2 uv) {
      return uv.x >= 1.0 - progress ? getToColor(uv) : getFromColor(uv);
    }
    """#,
    "wipeRight": #"""
    vec4 transition(CTX_PARAMS, vec2 uv) {
      return uv.x < progress ? getToColor(uv) : getFromColor(uv);
    }
    """#,
    "wipeUp": #"""
    vec4 transition(CTX_PARAMS, vec2 uv) {
      return uv.y < progress ? getToColor(uv) : getFromColor(uv);
    }
    """#,
    "wipeDown": #"""
    vec4 transition(CTX_PARAMS, vec2 uv) {
      return uv.y >= 1.0 - progress ? getToColor(uv) : getFromColor(uv);
    }
    """#,
    "softWipe": #"""
    #define SOFTNESS 0.15

    vec4 transition(CTX_PARAMS, vec2 uv) {
      float d = (uv.x + uv.y) * 0.5;
      float edge = progress * (1.0 + SOFTNESS);
      float t = 1.0 - smoothstep(edge - SOFTNESS, edge, d);
      return mix(getFromColor(uv), getToColor(uv), t);
    }
    """#,
    "clockWipe": #"""
    #define PI 3.14159265

    vec4 transition(CTX_PARAMS, vec2 uv) {
      vec2 d = uv - vec2(0.5);
      d.x *= ratio;
      float a = atan(d.x, d.y);
      if (a < 0.0) a += 2.0 * PI;
      return a / (2.0 * PI) < progress ? getToColor(uv) : getFromColor(uv);
    }
    """#,
    "barnDoorHorizontal": #"""
    vec4 transition(CTX_PARAMS, vec2 uv) {
      return abs(uv.x - 0.5) < progress * 0.5 ? getToColor(uv) : getFromColor(uv);
    }
    """#,
    "barnDoorVertical": #"""
    vec4 transition(CTX_PARAMS, vec2 uv) {
      return abs(uv.y - 0.5) < progress * 0.5 ? getToColor(uv) : getFromColor(uv);
    }
    """#,
    "blinds": #"""
    #define SLATS 10.0

    vec4 transition(CTX_PARAMS, vec2 uv) {
      return fract(uv.y * SLATS) < progress ? getToColor(uv) : getFromColor(uv);
    }
    """#,
    "stripes": #"""
    #define BANDS 8.0

    vec4 transition(CTX_PARAMS, vec2 uv) {
      float s = (uv.x + uv.y) * 0.5 * BANDS;
      float delay = floor(s) / BANDS * 0.5;
      float local = clamp((progress - delay) / 0.5, 0.0, 1.0);
      return fract(s) < local ? getToColor(uv) : getFromColor(uv);
    }
    """#,
    "zoomIn": #"""
    vec4 transition(CTX_PARAMS, vec2 uv) {
      vec4 grown = getFromColor((uv - vec2(0.5)) / (1.0 + 0.6 * progress) + vec2(0.5));
      return mix(grown, getToColor(uv), progress);
    }
    """#,
    "zoomOut": #"""
    vec4 transition(CTX_PARAMS, vec2 uv) {
      vec4 close = getToColor((uv - vec2(0.5)) / (1.6 - 0.6 * progress) + vec2(0.5));
      return mix(getFromColor(uv), close, progress);
    }
    """#,
    "crossZoom": #"""
    #define SAMPLES 12

    vec4 transition(CTX_PARAMS, vec2 uv) {
      float strength = sin(progress * 3.14159265) * 0.3;
      vec2 dir = uv - vec2(0.5);
      vec4 a = vec4(0.0);
      vec4 b = vec4(0.0);
      for (int i = 0; i < SAMPLES; i++) {
        vec2 q = vec2(0.5) + dir * (1.0 - strength * float(i) / float(SAMPLES));
        a += getFromColor(q);
        b += getToColor(q);
      }
      return mix(a / float(SAMPLES), b / float(SAMPLES), smoothstep(0.3, 0.7, progress));
    }
    """#,
    "spin": #"""
    #define PI 3.14159265

    vec2 turn(CTX_PARAMS, vec2 v, float a) {
      float c = cos(a);
      float s = sin(a);
      return vec2(c * v.x - s * v.y, s * v.x + c * v.y);
    }

    vec4 transition(CTX_PARAMS, vec2 uv) {
      vec4 to = getToColor(uv);
      float scale = 1.0 - progress;
      if (scale < 0.001) return to;
      vec2 d = uv - vec2(0.5);
      d.x *= ratio;
      vec2 q = turn(CTX_ARGS, d, -progress * PI) / scale;
      q.x /= ratio;
      q += vec2(0.5);
      if (q.x < 0.0 || q.x > 1.0 || q.y < 0.0 || q.y > 1.0) return to;
      return mix(getFromColor(q), to, progress * progress);
    }
    """#,
    "swirl": #"""
    vec4 transition(CTX_PARAMS, vec2 uv) {
      float strength = sin(progress * 3.14159265) * 6.0;
      vec2 d = uv - vec2(0.5);
      d.x *= ratio;
      float a = strength * max(0.0, 0.5 - length(d));
      float c = cos(a);
      float s = sin(a);
      vec2 q = vec2(c * d.x - s * d.y, s * d.x + c * d.y);
      q.x /= ratio;
      q = clamp(q + vec2(0.5), vec2(0.0), vec2(1.0));
      return mix(getFromColor(q), getToColor(q), smoothstep(0.3, 0.7, progress));
    }
    """#,
    "zoomThrough": #"""
    vec4 transition(CTX_PARAMS, vec2 uv) {
      if (progress < 0.5) {
        return getFromColor((uv - vec2(0.5)) / (1.0 + progress * 4.0) + vec2(0.5));
      }
      return getToColor((uv - vec2(0.5)) / (1.0 + (1.0 - progress) * 4.0) + vec2(0.5));
    }
    """#,
    "circleOpen": #"""
    vec4 transition(CTX_PARAMS, vec2 uv) {
      vec2 d = uv - vec2(0.5);
      d.x *= ratio;
      float r = progress * (length(vec2(0.5 * ratio, 0.5)) + 0.02);
      float t = 1.0 - smoothstep(r - 0.02, r, length(d));
      return mix(getFromColor(uv), getToColor(uv), t);
    }
    """#,
    "circleClose": #"""
    vec4 transition(CTX_PARAMS, vec2 uv) {
      vec2 d = uv - vec2(0.5);
      d.x *= ratio;
      float r = (1.0 - progress) * (length(vec2(0.5 * ratio, 0.5)) + 0.02);
      float t = smoothstep(r - 0.02, r, length(d));
      return mix(getFromColor(uv), getToColor(uv), t);
    }
    """#,
    "diamond": #"""
    vec4 transition(CTX_PARAMS, vec2 uv) {
      vec2 d = abs(uv - vec2(0.5));
      d.x *= ratio;
      float r = progress * (0.5 * ratio + 0.5 + 0.02);
      float t = 1.0 - smoothstep(r - 0.02, r, d.x + d.y);
      return mix(getFromColor(uv), getToColor(uv), t);
    }
    """#,
    "heart": #"""
    bool inHeart(CTX_PARAMS, vec2 p) {
      float a = p.x * p.x + p.y * p.y - 1.0;
      return a * a * a - p.x * p.x * p.y * p.y * p.y <= 0.0;
    }

    vec4 transition(CTX_PARAMS, vec2 uv) {
      if (progress >= 0.999) return getToColor(uv);
      // Grows slowly at first so the shape shows; 1.5 covers every corner, in
      // portrait and landscape.
      float s = progress * progress * 1.5;
      if (s < 0.0001) return getFromColor(uv);
      vec2 d = uv - vec2(0.5);
      d.x *= ratio;
      return inHeart(CTX_ARGS, d / s) ? getToColor(uv) : getFromColor(uv);
    }
    """#,
    "squares": #"""
    #define GRID 10.0

    vec4 transition(CTX_PARAMS, vec2 uv) {
      vec2 cells = vec2(GRID * ratio, GRID);
      vec2 f = fract(uv * cells) - vec2(0.5);
      vec2 c = (floor(uv * cells) + vec2(0.5)) / cells - vec2(0.5);
      c.x *= ratio;
      float delay = length(c) / length(vec2(0.5 * ratio, 0.5)) * 0.5;
      float local = clamp((progress - delay) / 0.5, 0.0, 1.0);
      return max(abs(f.x), abs(f.y)) <= local * 0.5 + 0.001 && local > 0.0
        ? getToColor(uv)
        : getFromColor(uv);
    }
    """#,
    "checkerboard": #"""
    #define GRID 8.0

    vec4 transition(CTX_PARAMS, vec2 uv) {
      vec2 cell = floor(uv * vec2(GRID * ratio, GRID));
      float odd = mod(cell.x + cell.y, 2.0);
      float t = clamp(progress * 2.0 - odd, 0.0, 1.0);
      return mix(getFromColor(uv), getToColor(uv), t);
    }
    """#,
    "blur": #"""
    #define TAPS 16
    #define GOLDEN 2.39996323

    vec4 blurFrom(CTX_PARAMS, vec2 uv, float radius) {
      vec4 sum = vec4(0.0);
      for (int i = 0; i < TAPS; i++) {
        float fi = float(i);
        float r = radius * sqrt((fi + 0.5) / float(TAPS));
        vec2 q = uv + vec2(cos(fi * GOLDEN) / ratio, sin(fi * GOLDEN)) * r;
        sum += getFromColor(clamp(q, vec2(0.0), vec2(1.0)));
      }
      return sum / float(TAPS);
    }

    vec4 blurTo(CTX_PARAMS, vec2 uv, float radius) {
      vec4 sum = vec4(0.0);
      for (int i = 0; i < TAPS; i++) {
        float fi = float(i);
        float r = radius * sqrt((fi + 0.5) / float(TAPS));
        vec2 q = uv + vec2(cos(fi * GOLDEN) / ratio, sin(fi * GOLDEN)) * r;
        sum += getToColor(clamp(q, vec2(0.0), vec2(1.0)));
      }
      return sum / float(TAPS);
    }

    vec4 transition(CTX_PARAMS, vec2 uv) {
      float radius = sin(progress * 3.14159265) * 0.04;
      return mix(blurFrom(CTX_ARGS, uv, radius), blurTo(CTX_ARGS, uv, radius), smoothstep(0.4, 0.6, progress));
    }
    """#,
    "flash": #"""
    vec4 transition(CTX_PARAMS, vec2 uv) {
      vec4 c = progress < 0.5 ? getFromColor(uv) : getToColor(uv);
      float f = 1.0 - abs(progress - 0.5) * 2.0;
      return mix(c, vec4(1.0), f * f * f);
    }
    """#,
    "lightLeak": #"""
    vec4 transition(CTX_PARAMS, vec2 uv) {
      vec4 c = mix(getFromColor(uv), getToColor(uv), smoothstep(0.35, 0.65, progress));
      float x = (uv.x + uv.y * 0.3 - mix(-0.3, 1.6, progress)) * 3.0;
      float glow = exp(-x * x) * sin(progress * 3.14159265);
      vec3 leak = vec3(1.0, 0.6, 0.25) * glow;
      return vec4(vec3(1.0) - (vec3(1.0) - c.rgb) * (vec3(1.0) - leak), 1.0);
    }
    """#,
    "burn": #"""
    vec4 transition(CTX_PARAMS, vec2 uv) {
      float k = sin(progress * 3.14159265);
      vec4 c = mix(getFromColor(uv), getToColor(uv), smoothstep(0.4, 0.6, progress));
      vec3 burned = c.rgb * (1.0 + k * 3.0) + vec3(k * 0.2);
      return vec4(min(burned, vec3(1.0)), 1.0);
    }
    """#,
    "pixelate": #"""
    vec4 transition(CTX_PARAMS, vec2 uv) {
      float k = min(progress, 1.0 - progress) * 2.0;
      vec2 block = vec2(k * 0.06 / ratio, k * 0.06);
      vec2 q = uv;
      if (block.y > 0.0005) {
        q = clamp((floor(uv / block) + vec2(0.5)) * block, vec2(0.0), vec2(1.0));
      }
      return progress < 0.5 ? getFromColor(q) : getToColor(q);
    }
    """#,
    "glitch": #"""
    float hash(CTX_PARAMS, vec2 p) {
      vec3 p3 = fract(vec3(p.x, p.y, p.x) * 0.1031);
      p3 += dot(p3, vec3(p3.y, p3.z, p3.x) + 33.33);
      return fract((p3.x + p3.y) * p3.z);
    }

    vec4 pick(CTX_PARAMS, vec2 p) {
      return progress < 0.5 ? getFromColor(p) : getToColor(p);
    }

    vec4 transition(CTX_PARAMS, vec2 uv) {
      float k = sin(progress * 3.14159265);
      float row = floor(uv.y * 24.0);
      float step12 = floor(progress * 12.0);
      float jump = (hash(CTX_ARGS, vec2(row, step12)) - 0.5) * 0.2 * k;
      float on = step(0.6, hash(CTX_ARGS, vec2(step12, row + 7.0)));
      vec2 q = vec2(clamp(uv.x + jump * on, 0.0, 1.0), uv.y);
      float split = 0.02 * k;
      float r = pick(CTX_ARGS, vec2(clamp(q.x + split, 0.0, 1.0), q.y)).r;
      vec4 g = pick(CTX_ARGS, q);
      float b = pick(CTX_ARGS, vec2(clamp(q.x - split, 0.0, 1.0), q.y)).b;
      return vec4(r, g.g, b, 1.0);
    }
    """#,
    "rgbSplit": #"""
    vec4 pick(CTX_PARAMS, vec2 p) {
      return mix(getFromColor(p), getToColor(p), smoothstep(0.4, 0.6, progress));
    }

    vec4 transition(CTX_PARAMS, vec2 uv) {
      float offset = 0.03 * sin(progress * 3.14159265);
      float r = pick(CTX_ARGS, vec2(clamp(uv.x + offset, 0.0, 1.0), uv.y)).r;
      vec4 g = pick(CTX_ARGS, uv);
      float b = pick(CTX_ARGS, vec2(clamp(uv.x - offset, 0.0, 1.0), uv.y)).b;
      return vec4(r, g.g, b, 1.0);
    }
    """#,
    "noise": #"""
    float hash(CTX_PARAMS, vec2 p) {
      vec3 p3 = fract(vec3(p.x, p.y, p.x) * 0.1031);
      p3 += dot(p3, vec3(p3.y, p3.z, p3.x) + 33.33);
      return fract((p3.x + p3.y) * p3.z);
    }

    vec4 transition(CTX_PARAMS, vec2 uv) {
      vec4 c = progress < 0.5 ? getFromColor(uv) : getToColor(uv);
      float k = sin(progress * 3.14159265);
      float n = hash(CTX_ARGS, floor(uv * vec2(180.0 * ratio, 180.0)) + floor(progress * 30.0) * vec2(13.0, 7.0));
      return mix(c, vec4(n, n, n, 1.0), k * k * 0.85);
    }
    """#,
    "mosaic": #"""
    float hash(CTX_PARAMS, vec2 p) {
      vec3 p3 = fract(vec3(p.x, p.y, p.x) * 0.1031);
      p3 += dot(p3, vec3(p3.y, p3.z, p3.x) + 33.33);
      return fract((p3.x + p3.y) * p3.z);
    }

    #define GRID 6.0

    vec4 transition(CTX_PARAMS, vec2 uv) {
      float order = hash(CTX_ARGS, floor(uv * vec2(GRID * ratio, GRID)) + vec2(3.0, 5.0));
      return progress > order ? getToColor(uv) : getFromColor(uv);
    }
    """#,
    "ripple": #"""
    vec4 transition(CTX_PARAMS, vec2 uv) {
      vec2 d = uv - vec2(0.5);
      d.x *= ratio;
      float dist = length(d);
      vec2 dir = dist > 0.0001 ? d / dist : vec2(0.0);
      vec2 off = dir * sin(dist * 40.0 - progress * 20.0) * sin(progress * 3.14159265) * 0.03;
      off.x /= ratio;
      vec2 q = clamp(uv + off, vec2(0.0), vec2(1.0));
      return mix(getFromColor(q), getToColor(q), smoothstep(0.3, 0.7, progress));
    }
    """#,
    "wave": #"""
    vec4 transition(CTX_PARAMS, vec2 uv) {
      float x = uv.x + sin(uv.y * 12.0 + progress * 10.0) * 0.04 * sin(progress * 3.14159265);
      vec2 q = vec2(clamp(x, 0.0, 1.0), uv.y);
      return mix(getFromColor(q), getToColor(q), smoothstep(0.3, 0.7, progress));
    }
    """#,
    "cube": #"""
    #define DEPTH 0.2

    vec4 face(CTX_PARAMS, vec2 p, float scale, bool incoming) {
      float y = (p.y - 0.5) / scale + 0.5;
      if (y < 0.0 || y > 1.0) return vec4(0.0, 0.0, 0.0, 1.0);
      return incoming ? getToColor(vec2(p.x, y)) : getFromColor(vec2(p.x, y));
    }

    vec4 transition(CTX_PARAMS, vec2 uv) {
      float split = 1.0 - progress;
      if (uv.x < split) {
        float x = uv.x / split;
        return face(CTX_ARGS, vec2(x, uv.y), mix(1.0 - DEPTH * progress, 1.0, x), false);
      }
      float x = (uv.x - split) / max(progress, 0.0001);
      return face(CTX_ARGS, vec2(x, uv.y), mix(1.0, 1.0 - DEPTH * (1.0 - progress), x), true);
    }
    """#,
    "doorway": #"""
    vec4 transition(CTX_PARAMS, vec2 uv) {
      float gap = 0.5 * progress;
      if (uv.x < 0.5 - gap) return getFromColor(vec2(uv.x + gap, uv.y));
      if (uv.x > 0.5 + gap) return getFromColor(vec2(uv.x - gap, uv.y));
      float s = 0.8 + 0.2 * progress;
      vec2 q = (uv - vec2(0.5)) / s + vec2(0.5);
      if (q.x < 0.0 || q.x > 1.0 || q.y < 0.0 || q.y > 1.0) return vec4(0.0, 0.0, 0.0, 1.0);
      return getToColor(q);
    }
    """#,
    "kaleidoscope": #"""
    #define PI 3.14159265
    #define SEGMENT 1.04719755

    vec4 transition(CTX_PARAMS, vec2 uv) {
      float k = sin(progress * PI);
      vec2 d = uv - vec2(0.5);
      d.x *= ratio;
      float r = length(d);
      float a = mod(atan(d.y, d.x) + progress * 2.0, SEGMENT);
      a = abs(a - SEGMENT * 0.5);
      float turn = a + progress * PI;
      vec2 kd = vec2(cos(turn), sin(turn)) * r * (1.0 + k);
      kd.x /= ratio;
      vec2 q = mix(uv, clamp(kd + vec2(0.5), vec2(0.0), vec2(1.0)), k);
      return mix(getFromColor(q), getToColor(q), smoothstep(0.4, 0.6, progress));
    }
    """#,
    "bounce": #"""
    float bounceOut(CTX_PARAMS, float t) {
      if (t < 1.0 / 2.75) return 7.5625 * t * t;
      if (t < 2.0 / 2.75) {
        float u = t - 1.5 / 2.75;
        return 7.5625 * u * u + 0.75;
      }
      if (t < 2.5 / 2.75) {
        float u = t - 2.25 / 2.75;
        return 7.5625 * u * u + 0.9375;
      }
      float u = t - 2.625 / 2.75;
      return 7.5625 * u * u + 0.984375;
    }

    vec4 transition(CTX_PARAMS, vec2 uv) {
      float off = 1.0 - bounceOut(CTX_ARGS, progress);
      return uv.y >= off ? getToColor(vec2(uv.x, uv.y - off)) : getFromColor(uv);
    }
    """#,
  ]
}
