// Generated by tool/gen_transitions.dart from transitions/*.glsl. Do not edit.

/// Groups of transitions, in the order the transitions sheet shows them.
enum TransitionCategory { basic, slide, wipe, zoom, shape, light, glitch, fun }

/// A transition the engines know, by the id projects store.
final class TransitionSpec {
  const TransitionSpec(this.id, this.category, {this.tolerance});

  final String id;
  final TransitionCategory category;

  /// How far the engines may stray from the reference images (0 to 1,
  /// mean per channel); noisy transitions get more.
  final double? tolerance;
}

/// Every transition, grouped by category.
const transitionCatalog = <TransitionSpec>[
  TransitionSpec('crossfade', TransitionCategory.basic),
  TransitionSpec('fadeToBlack', TransitionCategory.basic),
  TransitionSpec('fadeToWhite', TransitionCategory.basic),
  TransitionSpec('dissolve', TransitionCategory.basic, tolerance: 0.08),
  TransitionSpec('lumaFade', TransitionCategory.basic),
  TransitionSpec('slideLeft', TransitionCategory.slide),
  TransitionSpec('slideRight', TransitionCategory.slide),
  TransitionSpec('slideUp', TransitionCategory.slide),
  TransitionSpec('slideDown', TransitionCategory.slide),
  TransitionSpec('coverLeft', TransitionCategory.slide),
  TransitionSpec('coverRight', TransitionCategory.slide),
  TransitionSpec('revealLeft', TransitionCategory.slide),
  TransitionSpec('revealRight', TransitionCategory.slide),
  TransitionSpec('wipeLeft', TransitionCategory.wipe),
  TransitionSpec('wipeRight', TransitionCategory.wipe),
  TransitionSpec('wipeUp', TransitionCategory.wipe),
  TransitionSpec('wipeDown', TransitionCategory.wipe),
  TransitionSpec('softWipe', TransitionCategory.wipe),
  TransitionSpec('clockWipe', TransitionCategory.wipe),
  TransitionSpec('barnDoorHorizontal', TransitionCategory.wipe),
  TransitionSpec('barnDoorVertical', TransitionCategory.wipe),
  TransitionSpec('blinds', TransitionCategory.wipe),
  TransitionSpec('stripes', TransitionCategory.wipe),
  TransitionSpec('zoomIn', TransitionCategory.zoom),
  TransitionSpec('zoomOut', TransitionCategory.zoom),
  TransitionSpec('crossZoom', TransitionCategory.zoom, tolerance: 0.06),
  TransitionSpec('spin', TransitionCategory.zoom, tolerance: 0.06),
  TransitionSpec('swirl', TransitionCategory.zoom, tolerance: 0.06),
  TransitionSpec('zoomThrough', TransitionCategory.zoom),
  TransitionSpec('circleOpen', TransitionCategory.shape),
  TransitionSpec('circleClose', TransitionCategory.shape),
  TransitionSpec('diamond', TransitionCategory.shape),
  TransitionSpec('heart', TransitionCategory.shape),
  TransitionSpec('squares', TransitionCategory.shape),
  TransitionSpec('checkerboard', TransitionCategory.shape),
  TransitionSpec('blur', TransitionCategory.light, tolerance: 0.06),
  TransitionSpec('flash', TransitionCategory.light),
  TransitionSpec('lightLeak', TransitionCategory.light),
  TransitionSpec('burn', TransitionCategory.light),
  TransitionSpec('pixelate', TransitionCategory.glitch, tolerance: 0.06),
  TransitionSpec('glitch', TransitionCategory.glitch, tolerance: 0.08),
  TransitionSpec('rgbSplit', TransitionCategory.glitch),
  TransitionSpec('noise', TransitionCategory.glitch, tolerance: 0.1),
  TransitionSpec('mosaic', TransitionCategory.glitch, tolerance: 0.08),
  TransitionSpec('ripple', TransitionCategory.fun, tolerance: 0.06),
  TransitionSpec('wave', TransitionCategory.fun, tolerance: 0.06),
  TransitionSpec('cube', TransitionCategory.fun, tolerance: 0.06),
  TransitionSpec('doorway', TransitionCategory.fun),
  TransitionSpec('kaleidoscope', TransitionCategory.fun, tolerance: 0.08),
  TransitionSpec('bounce', TransitionCategory.fun),
];
