// Autogenerated from Pigeon (v29.0.2), do not edit directly.
// See also: https://pub.dev/packages/pigeon
// ignore_for_file: unused_import, unused_shown_name
// ignore_for_file: type=lint

import 'dart:async';
import 'dart:typed_data' show Float64List, Int32List, Int64List;

import 'package:flutter/services.dart';
import 'package:meta/meta.dart' show immutable, protected, visibleForTesting;

Object? _extractReplyValueOrThrow(
  List<Object?>? replyList,
  String channelName, {
  required bool isNullValid,
}) {
  if (replyList == null) {
    throw PlatformException(
      code: 'channel-error',
      message: 'Unable to establish connection on channel: "$channelName".',
    );
  } else if (replyList.length > 1) {
    throw PlatformException(
      code: replyList[0]! as String,
      message: replyList[1] as String?,
      details: replyList[2],
    );
  } else if (!isNullValid && (replyList.isNotEmpty && replyList[0] == null)) {
    throw PlatformException(
      code: 'null-error',
      message: 'Host platform returned null value for non-null return value.',
    );
  }
  return replyList.firstOrNull;
}

List<Object?> wrapResponse({
  Object? result,
  PlatformException? error,
  bool empty = false,
}) {
  if (empty) {
    return <Object?>[];
  }
  if (error == null) {
    return <Object?>[result];
  }
  return <Object?>[error.code, error.message, error.details];
}

bool _deepEquals(Object? a, Object? b) {
  if (identical(a, b)) {
    return true;
  }
  if (a is double && b is double) {
    if (a.isNaN && b.isNaN) {
      return true;
    }
    return a == b;
  }
  if (a is List && b is List) {
    return a.length == b.length &&
        a.indexed.every(
          ((int, dynamic) item) => _deepEquals(item.$2, b[item.$1]),
        );
  }
  if (a is Map && b is Map) {
    if (a.length != b.length) {
      return false;
    }
    for (final MapEntry<Object?, Object?> entryA in a.entries) {
      bool found = false;
      for (final MapEntry<Object?, Object?> entryB in b.entries) {
        if (_deepEquals(entryA.key, entryB.key)) {
          if (_deepEquals(entryA.value, entryB.value)) {
            found = true;
            break;
          } else {
            return false;
          }
        }
      }
      if (!found) {
        return false;
      }
    }
    return true;
  }
  return a == b;
}

int _deepHash(Object? value) {
  if (value is List) {
    return Object.hashAll(value.map(_deepHash));
  }
  if (value is Map) {
    int result = 0;
    for (final MapEntry<Object?, Object?> entry in value.entries) {
      result += (_deepHash(entry.key) * 31) ^ _deepHash(entry.value);
    }
    return result;
  }
  if (value is double && value.isNaN) {
    // Normalize NaN to a consistent hash.
    return 0x7FF8000000000000.hashCode;
  }
  if (value is double && value == 0.0) {
    // Normalize -0.0 to 0.0 so they have the same hash code.
    return 0.0.hashCode;
  }
  return value.hashCode;
}

/// What a media file contains, from the file itself.
class MediaInfoMessage {
  MediaInfoMessage({
    this.durationUs,
    required this.width,
    required this.height,
    required this.rotationDeg,
    required this.frameRate,
    required this.hasVideo,
    required this.hasAudio,
    required this.isHdr,
  });

  /// Null for still images.
  int? durationUs;

  /// Display size, after applying [rotationDeg].
  int width;

  int height;

  int rotationDeg;

  /// Nominal frame rate; zero for stills and audio.
  double frameRate;

  bool hasVideo;

  bool hasAudio;

  bool isHdr;

  List<Object?> _toList() {
    return <Object?>[
      durationUs,
      width,
      height,
      rotationDeg,
      frameRate,
      hasVideo,
      hasAudio,
      isHdr,
    ];
  }

  Object encode() {
    return _toList();
  }

  static MediaInfoMessage decode(Object result) {
    result as List<Object?>;
    return MediaInfoMessage(
      durationUs: result[0] as int?,
      width: result[1]! as int,
      height: result[2]! as int,
      rotationDeg: result[3]! as int,
      frameRate: result[4]! as double,
      hasVideo: result[5]! as bool,
      hasAudio: result[6]! as bool,
      isHdr: result[7]! as bool,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! MediaInfoMessage || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(durationUs, other.durationUs) &&
        _deepEquals(width, other.width) &&
        _deepEquals(height, other.height) &&
        _deepEquals(rotationDeg, other.rotationDeg) &&
        _deepEquals(frameRate, other.frameRate) &&
        _deepEquals(hasVideo, other.hasVideo) &&
        _deepEquals(hasAudio, other.hasAudio) &&
        _deepEquals(isHdr, other.isHdr);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'MediaInfoMessage(durationUs: $durationUs, width: $width, height: $height, rotationDeg: $rotationDeg, frameRate: $frameRate, hasVideo: $hasVideo, hasAudio: $hasAudio, isHdr: $isHdr)';
  }
}

class CapabilitiesMessage {
  CapabilitiesMessage({required this.hevc, required this.max4k});

  bool hevc;

  bool max4k;

  List<Object?> _toList() {
    return <Object?>[hevc, max4k];
  }

  Object encode() {
    return _toList();
  }

  static CapabilitiesMessage decode(Object result) {
    result as List<Object?>;
    return CapabilitiesMessage(
      hevc: result[0]! as bool,
      max4k: result[1]! as bool,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! CapabilitiesMessage || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(hevc, other.hevc) && _deepEquals(max4k, other.max4k);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'CapabilitiesMessage(hevc: $hevc, max4k: $max4k)';
  }
}

class ExportRequestMessage {
  ExportRequestMessage({
    required this.outputPath,
    required this.width,
    required this.height,
    required this.frameRate,
    required this.videoBitrate,
    required this.hevc,
  });

  String outputPath;

  int width;

  int height;

  int frameRate;

  int videoBitrate;

  bool hevc;

  List<Object?> _toList() {
    return <Object?>[outputPath, width, height, frameRate, videoBitrate, hevc];
  }

  Object encode() {
    return _toList();
  }

  static ExportRequestMessage decode(Object result) {
    result as List<Object?>;
    return ExportRequestMessage(
      outputPath: result[0]! as String,
      width: result[1]! as int,
      height: result[2]! as int,
      frameRate: result[3]! as int,
      videoBitrate: result[4]! as int,
      hevc: result[5]! as bool,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! ExportRequestMessage || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(outputPath, other.outputPath) &&
        _deepEquals(width, other.width) &&
        _deepEquals(height, other.height) &&
        _deepEquals(frameRate, other.frameRate) &&
        _deepEquals(videoBitrate, other.videoBitrate) &&
        _deepEquals(hevc, other.hevc);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'ExportRequestMessage(outputPath: $outputPath, width: $width, height: $height, frameRate: $frameRate, videoBitrate: $videoBitrate, hevc: $hevc)';
  }
}

class PlaybackStateMessage {
  PlaybackStateMessage({
    required this.positionUs,
    required this.durationUs,
    required this.isPlaying,
    required this.isBuffering,
  });

  int positionUs;

  int durationUs;

  bool isPlaying;

  bool isBuffering;

  List<Object?> _toList() {
    return <Object?>[positionUs, durationUs, isPlaying, isBuffering];
  }

  Object encode() {
    return _toList();
  }

  static PlaybackStateMessage decode(Object result) {
    result as List<Object?>;
    return PlaybackStateMessage(
      positionUs: result[0]! as int,
      durationUs: result[1]! as int,
      isPlaying: result[2]! as bool,
      isBuffering: result[3]! as bool,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! PlaybackStateMessage || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(positionUs, other.positionUs) &&
        _deepEquals(durationUs, other.durationUs) &&
        _deepEquals(isPlaying, other.isPlaying) &&
        _deepEquals(isBuffering, other.isBuffering);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'PlaybackStateMessage(positionUs: $positionUs, durationUs: $durationUs, isPlaying: $isPlaying, isBuffering: $isBuffering)';
  }
}

class _PigeonCodec extends StandardMessageCodec {
  const _PigeonCodec();
  @override
  void writeValue(WriteBuffer buffer, Object? value) {
    if (value is int) {
      buffer.putUint8(4);
      buffer.putInt64(value);
    } else if (value is MediaInfoMessage) {
      buffer.putUint8(129);
      writeValue(buffer, value.encode());
    } else if (value is CapabilitiesMessage) {
      buffer.putUint8(130);
      writeValue(buffer, value.encode());
    } else if (value is ExportRequestMessage) {
      buffer.putUint8(131);
      writeValue(buffer, value.encode());
    } else if (value is PlaybackStateMessage) {
      buffer.putUint8(132);
      writeValue(buffer, value.encode());
    } else {
      super.writeValue(buffer, value);
    }
  }

  @override
  Object? readValueOfType(int type, ReadBuffer buffer) {
    switch (type) {
      case 129:
        return MediaInfoMessage.decode(readValue(buffer)!);
      case 130:
        return CapabilitiesMessage.decode(readValue(buffer)!);
      case 131:
        return ExportRequestMessage.decode(readValue(buffer)!);
      case 132:
        return PlaybackStateMessage.decode(readValue(buffer)!);
      default:
        return super.readValueOfType(type, buffer);
    }
  }
}

class EngineHostApi {
  /// Constructor for [EngineHostApi]. The [binaryMessenger] named argument is
  /// available for dependency injection. If it is left null, the default
  /// BinaryMessenger will be used which routes to the host platform.
  EngineHostApi({
    BinaryMessenger? binaryMessenger,
    String messageChannelSuffix = '',
  }) : pigeonVar_binaryMessenger = binaryMessenger,
       pigeonVar_messageChannelSuffix = messageChannelSuffix.isNotEmpty
           ? '.$messageChannelSuffix'
           : '';

  final BinaryMessenger? pigeonVar_binaryMessenger;
  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  final String pigeonVar_messageChannelSuffix;

  /// Creates the preview surface; returns the Flutter texture id.
  Future<int> createPreview() async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.stitch.EngineHostApi.createPreview$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return pigeonVar_replyValue! as int;
  }

  /// Replaces the document being previewed. See `EngineDocument` in Dart.
  Future<void> setDocument(String json) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.stitch.EngineHostApi.setDocument$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[json],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: true,
    );
  }

  Future<void> play() async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.stitch.EngineHostApi.play$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: true,
    );
  }

  Future<void> pause() async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.stitch.EngineHostApi.pause$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: true,
    );
  }

  /// [exact] false allows landing near the time, for fast scrubbing.
  Future<void> seek(int positionUs, bool exact) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.stitch.EngineHostApi.seek$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[positionUs, exact],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: true,
    );
  }

  /// Releases players, decoders, and caches. Safe to call repeatedly.
  Future<void> release() async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.stitch.EngineHostApi.release$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: true,
    );
  }

  Future<MediaInfoMessage> probe(String path) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.stitch.EngineHostApi.probe$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[path],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return pigeonVar_replyValue! as MediaInfoMessage;
  }

  /// Writes a JPEG per time into [outDir], each at most [maxSize] pixels on
  /// its longest side, and returns their paths in order (null on failure).
  Future<List<String?>> thumbnails(
    String path,
    List<int> timesUs,
    int maxSize,
    String outDir,
  ) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.stitch.EngineHostApi.thumbnails$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[path, timesUs, maxSize, outDir],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return (pigeonVar_replyValue! as List<Object?>).cast<String?>();
  }

  /// Writes a 720p copy of [path] to [outPath] for smooth preview.
  Future<void> createProxy(String path, String outPath) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.stitch.EngineHostApi.createProxy$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[path, outPath],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: true,
    );
  }

  Future<CapabilitiesMessage> capabilities() async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.stitch.EngineHostApi.capabilities$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return pigeonVar_replyValue! as CapabilitiesMessage;
  }

  /// Starts exporting the current document; progress arrives through
  /// [EngineFlutterApi]. Returns a job id.
  Future<String> startExport(ExportRequestMessage request) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.stitch.EngineHostApi.startExport$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[request],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return pigeonVar_replyValue! as String;
  }

  Future<void> cancelExport(String jobId) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.stitch.EngineHostApi.cancelExport$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[jobId],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: true,
    );
  }
}

abstract class EngineFlutterApi {
  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  void onPlaybackState(PlaybackStateMessage state);

  void onExportProgress(String jobId, double fraction);

  void onExportCompleted(String jobId, String outputPath);

  /// [code] is stable (for mapping to a message); [message] is for logs.
  void onExportFailed(String jobId, String code, String message);

  static void setUp(
    EngineFlutterApi? api, {
    BinaryMessenger? binaryMessenger,
    String messageChannelSuffix = '',
  }) {
    messageChannelSuffix = messageChannelSuffix.isNotEmpty
        ? '.$messageChannelSuffix'
        : '';
    {
      final pigeonVar_channel = BasicMessageChannel<Object?>(
        'dev.flutter.pigeon.stitch.EngineFlutterApi.onPlaybackState$messageChannelSuffix',
        pigeonChannelCodec,
        binaryMessenger: binaryMessenger,
      );
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          final List<Object?> args = message! as List<Object?>;
          final PlaybackStateMessage arg_state =
              args[0]! as PlaybackStateMessage;
          try {
            api.onPlaybackState(arg_state);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          } catch (e) {
            return wrapResponse(
              error: PlatformException(code: 'error', message: e.toString()),
            );
          }
        });
      }
    }
    {
      final pigeonVar_channel = BasicMessageChannel<Object?>(
        'dev.flutter.pigeon.stitch.EngineFlutterApi.onExportProgress$messageChannelSuffix',
        pigeonChannelCodec,
        binaryMessenger: binaryMessenger,
      );
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          final List<Object?> args = message! as List<Object?>;
          final String arg_jobId = args[0]! as String;
          final double arg_fraction = args[1]! as double;
          try {
            api.onExportProgress(arg_jobId, arg_fraction);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          } catch (e) {
            return wrapResponse(
              error: PlatformException(code: 'error', message: e.toString()),
            );
          }
        });
      }
    }
    {
      final pigeonVar_channel = BasicMessageChannel<Object?>(
        'dev.flutter.pigeon.stitch.EngineFlutterApi.onExportCompleted$messageChannelSuffix',
        pigeonChannelCodec,
        binaryMessenger: binaryMessenger,
      );
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          final List<Object?> args = message! as List<Object?>;
          final String arg_jobId = args[0]! as String;
          final String arg_outputPath = args[1]! as String;
          try {
            api.onExportCompleted(arg_jobId, arg_outputPath);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          } catch (e) {
            return wrapResponse(
              error: PlatformException(code: 'error', message: e.toString()),
            );
          }
        });
      }
    }
    {
      final pigeonVar_channel = BasicMessageChannel<Object?>(
        'dev.flutter.pigeon.stitch.EngineFlutterApi.onExportFailed$messageChannelSuffix',
        pigeonChannelCodec,
        binaryMessenger: binaryMessenger,
      );
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          final List<Object?> args = message! as List<Object?>;
          final String arg_jobId = args[0]! as String;
          final String arg_code = args[1]! as String;
          final String arg_message = args[2]! as String;
          try {
            api.onExportFailed(arg_jobId, arg_code, arg_message);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          } catch (e) {
            return wrapResponse(
              error: PlatformException(code: 'error', message: e.toString()),
            );
          }
        });
      }
    }
  }
}
