#version 460 core
// Generated by tool/gen_transitions.dart from transitions/*.glsl. Do not edit.

#include <flutter/runtime_effect.glsl>

// Canvas size in pixels (xy), progress (z), and width over height (w), in
// one uniform so none can be dropped as unused.
uniform vec4 uParams;
uniform sampler2D uFrom;
uniform sampler2D uTo;

out vec4 fragColor;

#define progress uParams.z
#define ratio uParams.w

// Images are stored top row first; transitions use y up.
vec4 getFromColor(vec2 p) {
  return texture(uFrom, vec2(p.x, 1.0 - p.y));
}

vec4 getToColor(vec2 p) {
  return texture(uTo, vec2(p.x, 1.0 - p.y));
}

#define TAPS 16
#define GOLDEN 2.39996323

vec4 blurFrom(vec2 uv, float radius) {
  vec4 sum = vec4(0.0);
  for (int i = 0; i < TAPS; i++) {
    float fi = float(i);
    float r = radius * sqrt((fi + 0.5) / float(TAPS));
    vec2 q = uv + vec2(cos(fi * GOLDEN) / ratio, sin(fi * GOLDEN)) * r;
    sum += getFromColor(clamp(q, vec2(0.0), vec2(1.0)));
  }
  return sum / float(TAPS);
}

vec4 blurTo(vec2 uv, float radius) {
  vec4 sum = vec4(0.0);
  for (int i = 0; i < TAPS; i++) {
    float fi = float(i);
    float r = radius * sqrt((fi + 0.5) / float(TAPS));
    vec2 q = uv + vec2(cos(fi * GOLDEN) / ratio, sin(fi * GOLDEN)) * r;
    sum += getToColor(clamp(q, vec2(0.0), vec2(1.0)));
  }
  return sum / float(TAPS);
}

vec4 transition(vec2 uv) {
  float radius = sin(progress * 3.14159265) * 0.04;
  return mix(blurFrom(uv, radius), blurTo(uv, radius), smoothstep(0.4, 0.6, progress));
}

void main() {
  vec2 p = FlutterFragCoord().xy / uParams.xy;
  fragColor = transition(vec2(p.x, 1.0 - p.y));
}
