#version 460 core
// Generated by tool/gen_transitions.dart from transitions/*.glsl. Do not edit.

#include <flutter/runtime_effect.glsl>

// Canvas size in pixels (xy), progress (z), and width over height (w), in
// one uniform so none can be dropped as unused.
uniform vec4 uParams;
uniform sampler2D uFrom;
uniform sampler2D uTo;

out vec4 fragColor;

#define progress uParams.z
#define ratio uParams.w

// Images are stored top row first; transitions use y up.
vec4 getFromColor(vec2 p) {
  return texture(uFrom, vec2(p.x, 1.0 - p.y));
}

vec4 getToColor(vec2 p) {
  return texture(uTo, vec2(p.x, 1.0 - p.y));
}

#define SAMPLES 12

vec4 transition(vec2 uv) {
  float strength = sin(progress * 3.14159265) * 0.3;
  vec2 dir = uv - vec2(0.5);
  vec4 a = vec4(0.0);
  vec4 b = vec4(0.0);
  for (int i = 0; i < SAMPLES; i++) {
    vec2 q = vec2(0.5) + dir * (1.0 - strength * float(i) / float(SAMPLES));
    a += getFromColor(q);
    b += getToColor(q);
  }
  return mix(a / float(SAMPLES), b / float(SAMPLES), smoothstep(0.3, 0.7, progress));
}

void main() {
  vec2 p = FlutterFragCoord().xy / uParams.xy;
  fragColor = transition(vec2(p.x, 1.0 - p.y));
}
