#version 460 core
// Generated by tool/gen_transitions.dart from transitions/*.glsl. Do not edit.

#include <flutter/runtime_effect.glsl>

// Canvas size in pixels (xy), progress (z), and width over height (w), in
// one uniform so none can be dropped as unused.
uniform vec4 uParams;
uniform sampler2D uFrom;
uniform sampler2D uTo;

out vec4 fragColor;

#define progress uParams.z
#define ratio uParams.w

// Images are stored top row first; transitions use y up.
vec4 getFromColor(vec2 p) {
  return texture(uFrom, vec2(p.x, 1.0 - p.y));
}

vec4 getToColor(vec2 p) {
  return texture(uTo, vec2(p.x, 1.0 - p.y));
}

#define DEPTH 0.2

vec4 face(vec2 p, float scale, bool incoming) {
  float y = (p.y - 0.5) / scale + 0.5;
  if (y < 0.0 || y > 1.0) return vec4(0.0, 0.0, 0.0, 1.0);
  return incoming ? getToColor(vec2(p.x, y)) : getFromColor(vec2(p.x, y));
}

vec4 transition(vec2 uv) {
  float split = 1.0 - progress;
  if (uv.x < split) {
    float x = uv.x / split;
    return face(vec2(x, uv.y), mix(1.0 - DEPTH * progress, 1.0, x), false);
  }
  float x = (uv.x - split) / max(progress, 0.0001);
  return face(vec2(x, uv.y), mix(1.0, 1.0 - DEPTH * (1.0 - progress), x), true);
}

void main() {
  vec2 p = FlutterFragCoord().xy / uParams.xy;
  fragColor = transition(vec2(p.x, 1.0 - p.y));
}
