#version 460 core
// Generated by tool/gen_transitions.dart from transitions/*.glsl. Do not edit.

#include <flutter/runtime_effect.glsl>

// Canvas size in pixels (xy), progress (z), and width over height (w), in
// one uniform so none can be dropped as unused.
uniform vec4 uParams;
uniform sampler2D uFrom;
uniform sampler2D uTo;

out vec4 fragColor;

#define progress uParams.z
#define ratio uParams.w

// Images are stored top row first; transitions use y up.
vec4 getFromColor(vec2 p) {
  return texture(uFrom, vec2(p.x, 1.0 - p.y));
}

vec4 getToColor(vec2 p) {
  return texture(uTo, vec2(p.x, 1.0 - p.y));
}

#define PI 3.14159265
#define SEGMENT 1.04719755

vec4 transition(vec2 uv) {
  float k = sin(progress * PI);
  vec2 d = uv - vec2(0.5);
  d.x *= ratio;
  float r = length(d);
  float a = mod(atan(d.y, d.x) + progress * 2.0, SEGMENT);
  a = abs(a - SEGMENT * 0.5);
  float turn = a + progress * PI;
  vec2 kd = vec2(cos(turn), sin(turn)) * r * (1.0 + k);
  kd.x /= ratio;
  vec2 q = mix(uv, clamp(kd + vec2(0.5), vec2(0.0), vec2(1.0)), k);
  return mix(getFromColor(q), getToColor(q), smoothstep(0.4, 0.6, progress));
}

void main() {
  vec2 p = FlutterFragCoord().xy / uParams.xy;
  fragColor = transition(vec2(p.x, 1.0 - p.y));
}
