#version 460 core
// Generated by tool/gen_transitions.dart from transitions/*.glsl. Do not edit.

#include <flutter/runtime_effect.glsl>

// Canvas size in pixels (xy), progress (z), and width over height (w), in
// one uniform so none can be dropped as unused.
uniform vec4 uParams;
uniform sampler2D uFrom;
uniform sampler2D uTo;

out vec4 fragColor;

#define progress uParams.z
#define ratio uParams.w

// Images are stored top row first; transitions use y up.
vec4 getFromColor(vec2 p) {
  return texture(uFrom, vec2(p.x, 1.0 - p.y));
}

vec4 getToColor(vec2 p) {
  return texture(uTo, vec2(p.x, 1.0 - p.y));
}

vec4 transition(vec2 uv) {
  float k = min(progress, 1.0 - progress) * 2.0;
  vec2 block = vec2(k * 0.06 / ratio, k * 0.06);
  vec2 q = uv;
  if (block.y > 0.0005) {
    q = clamp((floor(uv / block) + vec2(0.5)) * block, vec2(0.0), vec2(1.0));
  }
  return progress < 0.5 ? getFromColor(q) : getToColor(q);
}

void main() {
  vec2 p = FlutterFragCoord().xy / uParams.xy;
  fragColor = transition(vec2(p.x, 1.0 - p.y));
}
