#version 460 core
// Generated by tool/gen_transitions.dart from transitions/*.glsl. Do not edit.

#include <flutter/runtime_effect.glsl>

// Canvas size in pixels (xy), progress (z), and width over height (w), in
// one uniform so none can be dropped as unused.
uniform vec4 uParams;
uniform sampler2D uFrom;
uniform sampler2D uTo;

out vec4 fragColor;

#define progress uParams.z
#define ratio uParams.w

// Images are stored top row first; transitions use y up.
vec4 getFromColor(vec2 p) {
  return texture(uFrom, vec2(p.x, 1.0 - p.y));
}

vec4 getToColor(vec2 p) {
  return texture(uTo, vec2(p.x, 1.0 - p.y));
}

vec4 pick(vec2 p) {
  return mix(getFromColor(p), getToColor(p), smoothstep(0.4, 0.6, progress));
}

vec4 transition(vec2 uv) {
  float offset = 0.03 * sin(progress * 3.14159265);
  float r = pick(vec2(clamp(uv.x + offset, 0.0, 1.0), uv.y)).r;
  vec4 g = pick(uv);
  float b = pick(vec2(clamp(uv.x - offset, 0.0, 1.0), uv.y)).b;
  return vec4(r, g.g, b, 1.0);
}

void main() {
  vec2 p = FlutterFragCoord().xy / uParams.xy;
  fragColor = transition(vec2(p.x, 1.0 - p.y));
}
