#version 460 core
// Generated by tool/gen_transitions.dart from transitions/*.glsl. Do not edit.

#include <flutter/runtime_effect.glsl>

// Canvas size in pixels (xy), progress (z), and width over height (w), in
// one uniform so none can be dropped as unused.
uniform vec4 uParams;
uniform sampler2D uFrom;
uniform sampler2D uTo;

out vec4 fragColor;

#define progress uParams.z
#define ratio uParams.w

// Images are stored top row first; transitions use y up.
vec4 getFromColor(vec2 p) {
  return texture(uFrom, vec2(p.x, 1.0 - p.y));
}

vec4 getToColor(vec2 p) {
  return texture(uTo, vec2(p.x, 1.0 - p.y));
}

#define GRID 10.0

vec4 transition(vec2 uv) {
  vec2 cells = vec2(GRID * ratio, GRID);
  vec2 f = fract(uv * cells) - vec2(0.5);
  vec2 c = (floor(uv * cells) + vec2(0.5)) / cells - vec2(0.5);
  c.x *= ratio;
  float delay = length(c) / length(vec2(0.5 * ratio, 0.5)) * 0.5;
  float local = clamp((progress - delay) / 0.5, 0.0, 1.0);
  return max(abs(f.x), abs(f.y)) <= local * 0.5 + 0.001 && local > 0.0
    ? getToColor(uv)
    : getFromColor(uv);
}

void main() {
  vec2 p = FlutterFragCoord().xy / uParams.xy;
  fragColor = transition(vec2(p.x, 1.0 - p.y));
}
