#version 460 core
// Generated by tool/gen_transitions.dart from transitions/*.glsl. Do not edit.

#include <flutter/runtime_effect.glsl>

// Canvas size in pixels (xy), progress (z), and width over height (w), in
// one uniform so none can be dropped as unused.
uniform vec4 uParams;
uniform sampler2D uFrom;
uniform sampler2D uTo;

out vec4 fragColor;

#define progress uParams.z
#define ratio uParams.w

// Images are stored top row first; transitions use y up.
vec4 getFromColor(vec2 p) {
  return texture(uFrom, vec2(p.x, 1.0 - p.y));
}

vec4 getToColor(vec2 p) {
  return texture(uTo, vec2(p.x, 1.0 - p.y));
}

vec4 transition(vec2 uv) {
  float strength = sin(progress * 3.14159265) * 6.0;
  vec2 d = uv - vec2(0.5);
  d.x *= ratio;
  float a = strength * max(0.0, 0.5 - length(d));
  float c = cos(a);
  float s = sin(a);
  vec2 q = vec2(c * d.x - s * d.y, s * d.x + c * d.y);
  q.x /= ratio;
  q = clamp(q + vec2(0.5), vec2(0.0), vec2(1.0));
  return mix(getFromColor(q), getToColor(q), smoothstep(0.3, 0.7, progress));
}

void main() {
  vec2 p = FlutterFragCoord().xy / uParams.xy;
  fragColor = transition(vec2(p.x, 1.0 - p.y));
}
